### ISSUE TITLE
Current line and fully selected line are near indistinguishable

### ISSUE THREAD

**Issue by imfranklin** [dracula/nova#3]
Since `meta.text.selected` and `meta.cursor` have the same background colors, the only difference between the current line with no selection and a line that is fully selected is the few pixels of a gutter background having changed.

![lines](https://user-images.githubusercontent.com/440067/102283398-fbf65080-3ef7-11eb-8860-e5803ff24562.png)

The Coda Dracula theme (https://github.com/dracula/coda) used for current line what this Nova theme has defined for `meta.gutter.selected` — would you entertain a pull request setting `meta.cursor` and `meta.gutter.selected` to the same background color?

**Comment by bdielman** [comment]
Thanks for adding this issue. I'm looking into this, but I'd like to add a few more fixes along with this to bring the theme closer to the Dracula spec. I'm reaching out to maintainers of other themes to get a consensus on how some elements should be handled. I'll have a fix for this issue in the next release.

**Comment by imfranklin** [comment]
Appreciate it! I've just made the jump after years on Coda, and this was the only difference that seemed out of place. The one-line change of imfranklin/nova@9b2e8ae5339f1ae113025405cddf896bff8e620c and it feels like home again.

**Comment by bdielman** [comment]
One thing to note (and it's been a very long time since I've used Coda), it looks like the current line in the code is using `#44475a` (the selection color according to the spec), so I'm curious why you're seeing a different color in the editor. It was also used as the current line background in the Dracula theme for VSCode (until issues with how VSCode stacks colors made them change it in v1.5.0).

**Coda**: https://github.com/dracula/coda/blob/master/Dracula.sss#L27
**VSCode**: https://github.com/dracula/visual-studio-code/blob/v2.14.1/src/dracula.yml#L41

Like I mentioned, I'm reaching out to other maintainers of Dracula themes to make sure this follows the spec as I plan to get his integrated into their library. 🧛‍♂️

**Comment by imfranklin** [comment]
A fair question. I was relying on experience, not spec, though. Here's the Coda Dracula next to my modified version of your Nova Dracula — both looking at my same file:

![image](https://user-images.githubusercontent.com/440067/102377397-390b2300-3f8a-11eb-8a8e-3ec2a6d0d2e9.png)

And worth noting, the README image for https://github.com/dracula/coda displays the current line behavior I've been staring at for years:

![image](https://user-images.githubusercontent.com/440067/102378041-fb5aca00-3f8a-11eb-8775-5aa34d14371f.png)

**Comment by bdielman** [comment]
I'll definitely consider it. Thanks again for bringing up the issue!
